name: rllab3
channels:
    - https://conda.anaconda.org/kne 
    - https://conda.anaconda.org/tlatorre 
    - https://conda.anaconda.org/cjs14
    - https://conda.anaconda.org/menpo
    - jjhelmus
    - soumith
dependencies:
    - python==3.5.2
    - numpy
    - scipy
    - path.py
    - python-dateutil
    - joblib==0.10.3
    - mako
    - numba
    - pybox2d
    - pygame
    - matplotlib
    - opencv3=3.1.0
    - scikit-learn
    - mpi4py
    - pandas
    - pip:
        - Pillow
        - atari-py
        - pyprind
        - ipdb
        - PyOpenGL
        - pyzmq
        - tqdm
        - msgpack-python
        - git+https://github.com/inksci/mujoco-py-v0.5.7.git
        - cached_property
        - cloudpickle
        - Cython
        - keras==1.2.1
        - git+https://github.com/Theano/Theano.git@adfe319ce6b781083d8dc3200fb4481b00853791#egg=Theano
        - gym==0.10.3
        - pyglet
        - progressbar2
        - tensorflow-gpu==1.3.0
        - numpy-stl==2.2.0
        - nibabel==2.1.0
        - pylru==1.0.9
        - hyperopt
        - polling
